### ISSUE TITLE
S3 Express One Zone error: "Not implemented Error: Enum value: '' not implemented"

### ISSUE THREAD

**Issue by csmithxc** [tobilg/serverless-duckdb#5]
After uncommenting all AWS S3 Express One Zone lines in the config, deploying, and calling the `queryExpress` endpoint, I get the following error:
```
{"error":"Not implemented Error: Enum value: '' not implemented"}
```

I believe this is happening in the extension initialization.

For reference, I'm using `runtime: nodejs20.x` and the latest x86_64 layer `14`.

**Comment by tobilg** [comment]
Could you please post the full CloudWatch log (anonymized)?

**Comment by csmithxc** [comment]
Logs:
```
INIT_START Runtime Version: nodejs:16.v64	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:babdf21d739bfda4c9f34221ce1889f4857d277324ffe622cf48faa2e71917b3
START
{"name":"duckdb-sync-logger","hostname":"**************","pid":9,"requestId":"************************************","level":20,"event":{"resource":"/v1/queryS3Express","path":"/v1/queryS3Express","httpMethod":"POST","headers":{"Accept":"*/*","CloudFront-Forwarded-Proto":"https","CloudFront-Is-Desktop-Viewer":"true","CloudFront-Is-Mobile-Viewer":"false","CloudFront-Is-SmartTV-Viewer":"false","CloudFront-Is-Tablet-Viewer":"false","CloudFront-Viewer-ASN":"10796","CloudFront-Viewer-Country":"US","content-type":"application/json","Host":"[REDACTED].execute-api.us-east-1.amazonaws.com","User-Agent":"curl/8.7.1","Via":"2.0 dc258c6be709f7f39799b8fc175687ec.cloudfront.net (CloudFront)","X-Amz-Cf-Id":"FhFheWxxZqaWIXYZ1v-211EL_R-jgYPYzqwuTc1wFjH4Kiyuecg0lw==","X-Amzn-Trace-Id":"Root=1-67672e7c-3de0437c4162bb7741a4299e","x-api-key":"[REDACTED]","X-Forwarded-For":"*************, *************","X-Forwarded-Port":"443","X-Forwarded-Proto":"https"},"multiValueHeaders":{"Accept":["*/*"],"CloudFront-Forwarded-Proto":["https"],"CloudFront-Is-Desktop-Viewer":["true"],"CloudFront-Is-Mobile-Viewer":["false"],"CloudFront-Is-SmartTV-Viewer":["false"],"CloudFront-Is-Tablet-Viewer":["false"],"CloudFront-Viewer-ASN":["10796"],"CloudFront-Viewer-Country":["US"],"content-type":["application/json"],"Host":["naer1mro1b.execute-api.us-east-1.amazonaws.com"],"User-Agent":["curl/8.7.1"],"Via":["2.0 dc258c6be709f7f39799b8fc175687ec.cloudfront.net (CloudFront)"],"X-Amz-Cf-Id":["FhFheWxxZqaWIXYZ1v-211EL_R-jgYPYzqwuTc1wFjH4Kiyuecg0lw=="],"X-Amzn-Trace-Id":["Root=1-67672e7c-3de0437c4162bb7741a4299e"],"x-api-key":["[REDACTED]"],"X-Forwarded-For":["*************, *************"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"]},"queryStringParameters":null,"multiValueQueryStringParameters":null,"pathParameters":null,"stageVariables":null,"requestContext":{"resourceId":"x2edz3","resourcePath":"/v1/queryS3Express","httpMethod":"POST","extendedRequestId":"DKQzhG0FIAMEOIw=","requestTime":"21/Dec/2024:21:09:16 +0000","path":"/prd/v1/queryS3Express","accountId":"[REDACTED]","protocol":"HTTP/1.1","stage":"prd","domainPrefix":"naer1mro1b","requestTimeEpoch":1734815356549,"requestId":"************************************","identity":{"cognitoIdentityPoolId":null,"cognitoIdentityId":null,"apiKey":"[REDACTED]","principalOrgId":null,"cognitoAuthenticationType":null,"userArn":null,"apiKeyId":"[REDATED]","userAgent":"curl/8.7.1","accountId":null,"caller":null,"sourceIp":"*************","accessKey":null,"cognitoAuthenticationProvider":null,"user":null},"domainName":"naer1mro1b.execute-api.us-east-1.amazonaws.com","deploymentId":"iwknw0","apiId":"naer1mro1b"},"body":"{\n    \"filePath\": \"s3://[REDACTED]-serverless-duckdb--use1-az4--x-s3/lightning.parquet\"\n}","isBase64Encoded":false},"context":{"callbackWaitsForEmptyEventLoop":true,"functionVersion":"$LATEST","functionName":"serverless-duckdb-v3-prd-queryS3Express","memoryLimitInMB":"10240","logGroupName":"/aws/lambda/serverless-duckdb-v3-prd-queryS3Express","logStreamName":"2024/12/21/[$LATEST]606c9ef144f647e2b6d9f017bc926c08","invokedFunctionArn":"arn:aws:lambda:us-east-1:[REDACTED]:function:serverless-duckdb-v3-prd-queryS3Express","awsRequestId":"************************************"},"msg":"","time":"2024-12-21T21:09:17.246Z","v":0}
{"name":"duckdb-sync-logger","hostname":"**************","pid":9,"requestId":"************************************","level":50,"msg":"Error installing and loading local extensions: [Error: Not implemented Error: Enum value: '' not implemented] {\n  errno: -1,\n  code: 'DUCKDB_NODEJS_ERROR',\n  errorType: 'Not implemented'\n}","time":"2024-12-21T21:09:17.542Z","v":0}
{"name":"duckdb-sync-logger","hostname":"**************","pid":9,"requestId":"************************************","level":50,"err":{"message":"Not implemented Error: Enum value: '' not implemented","name":"Error","stack":"Error: Not implemented Error: Enum value: '' not implemented","code":"DUCKDB_NODEJS_ERROR"},"msg":"Not implemented Error: Enum value: '' not implemented","time":"2024-12-21T21:09:17.543Z","v":0}
2024-12-21 16:09:17.544	INFO	{"LogGroup":"serverless-duckdb-v3-prd-queryS3Express","ServiceName":"serverless-duckdb-v3-prd-queryS3Express","ServiceType":"AWS::Lambda::Function","Service":"QueryService","RequestId":"************************************","executionEnvironment":"AWS_Lambda_nodejs16.x","memorySize":"10240","functionVersion":"$LATEST","logStreamId":"2024/12/21/[$LATEST]606c9ef144f647e2b6d9f017bc926c08","_aws":{"Timestamp":1734815357246,"CloudWatchMetrics":[{"Dimensions":[["LogGroup","ServiceName","ServiceType","Service"]],"Metrics":[],"Namespace":"aws-embedded-metrics"}]}}
END Duration: 301.36 ms (init: 280.89 ms) Memory Used: 134 MB
```

After doing some testing, I'm very confident that it's occurring when any one of these extensions is installed/loaded.
```
await query(`INSTALL '/opt/nodejs/node_modules/duckdb/extensions/aws.duckdb_extension';`, false);
await query(`LOAD '/opt/nodejs/node_modules/duckdb/extensions/aws.duckdb_extension';`, false);
await query(`INSTALL '/opt/nodejs/node_modules/duckdb/extensions/httpfs.duckdb_extension';`, false);
await query(`LOAD '/opt/nodejs/node_modules/duckdb/extensions/httpfs.duckdb_extension';`, false);
await query(`INSTALL '/opt/nodejs/node_modules/duckdb/extensions/arrow.duckdb_extension';`, false);
await query(`LOAD '/opt/nodejs/node_modules/duckdb/extensions/arrow.duckdb_extension';`, false);
```

I did not change anything from what came with the serverless file. I even changed my nodejs version back to `16.x`. I've also insured that my duckdb version is `1.1.1` to match the layer's.

**Comment by tobilg** [comment]
Thanks, I‘ll see if I can reproduce the error. Will report back.

**Comment by csmithxc** [comment]
FWIW - I had the idea to run an experiment to see what would happen if the enum value `''` was initialized. I ran this above the extension installation lines:
```
await query(`CREATE TYPE nie AS ENUM ('');`, false);
```

I ran into a bit of a dead end after getting this subsequent error:
```
node: ../src/duckdb/src/parser/transform/statement/transform_create_type.cpp:31: duckdb::Vector duckdb::Transformer::PGListToVector(duckdb::optional_ptr<duckdb_libpgquery::PGList>, duckdb::idx_t&): Assertion `!entry_value.empty()' failed.
```

It looks like this allowed the extensions to install / load, but when I tried to run a trivial query like `SELECT 1;` I'd get this error.

**Comment by csmithxc** [comment]
Checking in - @tobilg did you get a chance to look at this? If you don't have time, where would be a good place to start trying to debug this? I assume it worked for you when initially committed.

**Comment by tobilg** [comment]
@csmithxc Please make sure that you use the appropriate layer, in the case of the S3 Express version the following: https://github.com/tobilg/serverless-duckdb/blob/main/serverless.yml#L129

Loading local extensions like in https://github.com/tobilg/serverless-duckdb/blob/main/src/functions/queryS3Express.ts#L77-L82 will NOT work when you use the `x86_64` layer, because they aren't included there...

**Comment by tobilg** [comment]
Or, you can use the remote extensions, but then like this: https://github.com/tobilg/serverless-duckdb/blob/main/src/functions/query.ts#L76-L82

**Comment by csmithxc** [comment]
@tobilg I should have edited the initial post, but I was actually using the appropriate v6 layer (just goofed when I was typing up the issue). Using the remote extensions is more attractive, but I'm not sure how this would work in the VPC. What settings would you recommend changing in the VPC configuration to make that work?

**Comment by tobilg** [comment]
Just allow outgoing internet traffic I guess...

**Comment by csmithxc** [comment]
I'll give that a shot then and update here with how it goes. Thanks for your continued support with this!

**Comment by csmithxc** [comment]
This worked! I added the following to my files:

In `resources/vpc.yml`
```yaml
  # Add Public Subnet for NAT Gateway
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZoneId: ${self:custom.s3.availabilityZoneId}
      CidrBlock: 10.0.2.0/23
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 'Public Subnet'

  # Route table for public subnet
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 'Public'

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # NAT Gateway configuration
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet

  # Add route to private subnet route table
  PrivateARouteToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateARouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
```

In `serverless.yml` under the `queryS3Express` function:
```yaml
# Add permissions for NAT Gateway
      - Effect: Allow
        Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
        Resource: "*"
```

I switched the function to use the same layer that `query` does, and s suggested, I used the same extension initialization procedure as `query`.
